version = 0.1

[default.deploy.parameters]
stack_name = "intern-diego-van-overberghe-pipeline-stack"
region = "eu-central-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"

resolve_s3 = false
s3_bucket = "transcality-intern"
s3_prefix = "diego-van-overberghe"
